import { Coordinates, calculateDistance } from './geo';

export interface Place {
  id: string;
  name: string;
  nameKo: string;
  category: string;
  address: string;
  latitude: number;
  longitude: number;
  budget_level: 'low' | 'medium' | 'high';
  description: string;
}

export const MOCK_PLACES: Place[] = [
  {
    id: '1',
    name: 'Maple Tree House',
    nameKo: '메이플트리하우스',
    category: 'Korean BBQ',
    address: '서울특별시 용산구 이태원동',
    latitude: 37.5343,
    longitude: 126.9947,
    budget_level: 'high',
    description: '분위기 좋은 프리미엄 한식 바비큐 맛집',
  },
  {
    id: '2',
    name: 'Myeongdong Kyoja',
    nameKo: '명동교자',
    category: 'Korean Traditional',
    address: '서울특별시 중구 명동2가',
    latitude: 37.5636,
    longitude: 126.9838,
    budget_level: 'low',
    description: '칼국수와 만두로 유명한 맛집',
  },
  {
    id: '3',
    name: 'Jungsik',
    nameKo: '정식',
    category: 'Korean Fine Dining',
    address: '서울특별시 강남구 청담동',
    latitude: 37.5236,
    longitude: 127.0411,
    budget_level: 'high',
    description: '미슐랭 스타를 받은 모던 한식 레스토랑',
  },
  {
    id: '4',
    name: 'Tosokchon Samgyetang',
    nameKo: '토속촌',
    category: 'Korean Traditional',
    address: '서울특별시 종로구',
    latitude: 37.5813,
    longitude: 126.9731,
    budget_level: 'medium',
    description: '유명한 인삼 닭백숙 전문점',
  },
  {
    id: '5',
    name: 'Sushi Cho',
    nameKo: '스시조',
    category: 'Japanese',
    address: '서울특별시 강남구 신사동',
    latitude: 37.5204,
    longitude: 127.0228,
    budget_level: 'high',
    description: '정통 에도마에 스타일 스시 전문점',
  },
  {
    id: '6',
    name: 'Hongdae Dakgalbi Street',
    nameKo: '홍대닭갈비',
    category: 'Korean',
    address: '서울특별시 마포구 홍대',
    latitude: 37.5563,
    longitude: 126.9235,
    budget_level: 'low',
    description: '매콤한 닭갈비 볶음 전문',
  },
  {
    id: '7',
    name: 'La Yeon',
    nameKo: '라연',
    category: 'Korean Fine Dining',
    address: '서울특별시 중구 소공동',
    latitude: 37.5652,
    longitude: 126.9779,
    budget_level: 'high',
    description: '미슐랭 3스타 한식 레스토랑',
  },
  {
    id: '8',
    name: 'Gwangjang Market',
    nameKo: '광장시장',
    category: 'Korean Street Food',
    address: '서울특별시 종로구',
    latitude: 37.5701,
    longitude: 126.9998,
    budget_level: 'low',
    description: '다양한 길거리 음식이 있는 전통 시장',
  },
  {
    id: '9',
    name: 'Pasta Jay',
    nameKo: '파스타제이',
    category: 'Italian',
    address: '서울특별시 강남구',
    latitude: 37.4979,
    longitude: 127.0276,
    budget_level: 'medium',
    description: '정통 이탈리안 파스타와 와인',
  },
  {
    id: '10',
    name: 'Mingles',
    nameKo: '밍글스',
    category: 'Korean Fusion',
    address: '서울특별시 강남구 청담동',
    latitude: 37.5264,
    longitude: 127.0396,
    budget_level: 'high',
    description: '모던 한식 퓨전 요리',
  },
  {
    id: '11',
    name: 'Noryangjin Fish Market',
    nameKo: '노량진수산시장',
    category: 'Seafood',
    address: '서울특별시 동작구 노량진동',
    latitude: 37.5121,
    longitude: 126.9423,
    budget_level: 'medium',
    description: '신선한 해산물 시장과 식당',
  },
  {
    id: '12',
    name: 'Cafe Onion',
    nameKo: '카페어니언',
    category: 'Cafe',
    address: '서울특별시 성동구 성수동',
    latitude: 37.5445,
    longitude: 127.0557,
    budget_level: 'low',
    description: '트렌디한 베이커리 카페',
  },
  {
    id: '13',
    name: 'Samwon Garden',
    nameKo: '삼원가든',
    category: 'Korean BBQ',
    address: '서울특별시 강남구 압구정동',
    latitude: 37.5292,
    longitude: 127.0282,
    budget_level: 'high',
    description: '전설적인 한식 바비큐 레스토랑',
  },
  {
    id: '14',
    name: 'Sulbing',
    nameKo: '설빙',
    category: 'Dessert',
    address: '서울특별시 여러 지역',
    latitude: 37.5172,
    longitude: 127.0473,
    budget_level: 'low',
    description: '한국식 눈꽃빙수 디저트',
  },
  {
    id: '15',
    name: 'Hanilkwan',
    nameKo: '한일관',
    category: 'Korean Traditional',
    address: '서울특별시 중구 명동',
    latitude: 37.5608,
    longitude: 126.9856,
    budget_level: 'medium',
    description: '1939년부터 이어져온 유서 깊은 한식당',
  },
  {
    id: '16',
    name: 'Mapo Jeong Daepo',
    nameKo: '마포정대포',
    category: 'Korean',
    address: '서울특별시 마포구',
    latitude: 37.5441,
    longitude: 126.9514,
    budget_level: 'medium',
    description: '돼지갈비 구이로 유명한 맛집',
  },
  {
    id: '17',
    name: 'Yongsusan',
    nameKo: '용수산',
    category: 'Seafood',
    address: '서울특별시 종로구',
    latitude: 37.5742,
    longitude: 126.9854,
    budget_level: 'medium',
    description: '신선한 해산물과 사시미 전문점',
  },
  {
    id: '18',
    name: 'Brick Oven',
    nameKo: '브릭오븐',
    category: 'Italian',
    address: '서울특별시 용산구',
    latitude: 37.5311,
    longitude: 126.9803,
    budget_level: 'medium',
    description: '화덕에서 구운 피자 전문점',
  },
  {
    id: '19',
    name: 'Born and Bred',
    nameKo: '본앤브레드',
    category: 'Korean BBQ',
    address: '서울특별시 용산구 이태원',
    latitude: 37.5346,
    longitude: 126.9931,
    budget_level: 'high',
    description: '프리미엄 한우 바비큐 전문점',
  },
  {
    id: '20',
    name: 'Naengmyeon Alley',
    nameKo: '냉면골목',
    category: 'Korean Traditional',
    address: '서울특별시 중구 을지로',
    latitude: 37.5664,
    longitude: 126.9918,
    budget_level: 'low',
    description: '냉면 전문점이 모여있는 거리',
  },
  {
    id: '21',
    name: 'Thai Orchid',
    nameKo: '타이오키드',
    category: 'Thai',
    address: '서울특별시 강남구',
    latitude: 37.5012,
    longitude: 127.0396,
    budget_level: 'medium',
    description: '정통 태국 요리 전문점',
  },
  {
    id: '22',
    name: 'Anthracite Coffee',
    nameKo: '앤쓰러사이트',
    category: 'Cafe',
    address: '서울특별시 마포구 합정동',
    latitude: 37.5493,
    longitude: 126.9134,
    budget_level: 'low',
    description: '인더스트리얼 스타일의 카페',
  },
  {
    id: '23',
    name: 'Gaon',
    nameKo: '가온',
    category: 'Korean Fine Dining',
    address: '서울특별시 강남구',
    latitude: 37.5177,
    longitude: 127.0229,
    budget_level: 'high',
    description: '미슐랭 3스타 레스토랑',
  },
  {
    id: '24',
    name: 'Balwoo Gongyang',
    nameKo: '발우공양',
    category: 'Korean Temple Food',
    address: '서울특별시 종로구',
    latitude: 37.5838,
    longitude: 126.9853,
    budget_level: 'medium',
    description: '사찰 음식 전문점',
  },
  {
    id: '25',
    name: 'Muoki',
    nameKo: '무오키',
    category: 'Japanese',
    address: '서울특별시 강남구 청담동',
    latitude: 37.5248,
    longitude: 127.0447,
    budget_level: 'high',
    description: '고급 일식 다이닝',
  },
  {
    id: '26',
    name: 'Gyeongbokgung Jip',
    nameKo: '경복궁집',
    category: 'Korean Traditional',
    address: '서울특별시 종로구',
    latitude: 37.5789,
    longitude: 126.9769,
    budget_level: 'low',
    description: '궁궐 근처의 전통 한식집',
  },
  {
    id: '27',
    name: 'Tartine',
    nameKo: '타르틴',
    category: 'Cafe',
    address: '서울특별시 용산구 한남동',
    latitude: 37.5337,
    longitude: 127.0025,
    budget_level: 'low',
    description: '베이커리 겸 카페',
  },
  {
    id: '28',
    name: 'Poom Seoul',
    nameKo: '품서울',
    category: 'Korean Fusion',
    address: '서울특별시 강남구',
    latitude: 37.5089,
    longitude: 127.0604,
    budget_level: 'medium',
    description: '모던 한식 다이닝',
  },
  {
    id: '29',
    name: 'Jinokhwa Halmae Wonjo Dakhanmari',
    nameKo: '진옥화할매원조닭한마리',
    category: 'Korean',
    address: '서울특별시 종로구',
    latitude: 37.5716,
    longitude: 127.0093,
    budget_level: 'low',
    description: '유명한 닭한마리 칼국수 맛집',
  },
  {
    id: '30',
    name: 'Eataly Seoul',
    nameKo: '이탈리서울',
    category: 'Italian',
    address: '서울특별시 용산구 이태원',
    latitude: 37.5342,
    longitude: 126.9946,
    budget_level: 'medium',
    description: '이탈리안 마켓플레이스 겸 레스토랑',
  },
  {
    id: '31',
    name: 'Vatos Urban Tacos',
    nameKo: '바토스',
    category: 'Mexican Fusion',
    address: '서울특별시 용산구 이태원',
    latitude: 37.5348,
    longitude: 126.9941,
    budget_level: 'medium',
    description: '한국-멕시코 퓨전 요리',
  },
  {
    id: '32',
    name: 'Sulwhasoo Flagship Store Cafe',
    nameKo: '설화수플래그십스토어',
    category: 'Cafe',
    address: '서울특별시 강남구',
    latitude: 37.5199,
    longitude: 127.0226,
    budget_level: 'low',
    description: '화장품 브랜드에서 운영하는 카페',
  },
  {
    id: '33',
    name: 'Baekje Samgyetang',
    nameKo: '백제삼계탕',
    category: 'Korean Traditional',
    address: '서울특별시 중구 명동',
    latitude: 37.5612,
    longitude: 126.9853,
    budget_level: 'medium',
    description: '인삼 닭백숙 전문점',
  },
  {
    id: '34',
    name: 'Yukjeon Hoekwan',
    nameKo: '육전회관',
    category: 'Korean BBQ',
    address: '서울특별시 마포구',
    latitude: 37.5487,
    longitude: 126.9142,
    budget_level: 'medium',
    description: '전통 한우 전문점',
  },
  {
    id: '35',
    name: 'Busan Sikdang',
    nameKo: '부산식당',
    category: 'Korean',
    address: '서울특별시 종로구',
    latitude: 37.5823,
    longitude: 126.9841,
    budget_level: 'low',
    description: '부산 스타일 해물탕',
  },
  {
    id: '36',
    name: 'Pierre Gagnaire Seoul',
    nameKo: '피에르가니에르',
    category: 'French',
    address: '서울특별시 중구',
    latitude: 37.5644,
    longitude: 126.9751,
    budget_level: 'high',
    description: '프렌치 파인 다이닝',
  },
  {
    id: '37',
    name: 'Gogung',
    nameKo: '고궁',
    category: 'Korean Traditional',
    address: '서울특별시 중구 명동',
    latitude: 37.5621,
    longitude: 126.9864,
    budget_level: 'medium',
    description: '비빔밥 전문점',
  },
  {
    id: '38',
    name: 'Jokbal Alley',
    nameKo: '족발골목',
    category: 'Korean',
    address: '서울특별시 중구 장충동',
    latitude: 37.5598,
    longitude: 127.0071,
    budget_level: 'low',
    description: '족발 전문점이 모여있는 거리',
  },
  {
    id: '39',
    name: 'Tongin Market Box Lunch Cafe',
    nameKo: '통인시장도시락카페',
    category: 'Korean Street Food',
    address: '서울특별시 종로구',
    latitude: 37.5802,
    longitude: 126.9671,
    budget_level: 'low',
    description: 'DIY 도시락 카페',
  },
  {
    id: '40',
    name: 'Sushi Sora',
    nameKo: '스시소라',
    category: 'Japanese',
    address: '서울특별시 중구',
    latitude: 37.5665,
    longitude: 126.9773,
    budget_level: 'high',
    description: '도시 전망의 프리미엄 스시',
  },
  {
    id: '41',
    name: 'Wangbijib',
    nameKo: '왕비집',
    category: 'Korean BBQ',
    address: '서울특별시 마포구',
    latitude: 37.5512,
    longitude: 126.9203,
    budget_level: 'medium',
    description: '인기 있는 돼지고기 바비큐 맛집',
  },
  {
    id: '42',
    name: 'Passion 5',
    nameKo: '패션파이브',
    category: 'Dessert',
    address: '서울특별시 강남구',
    latitude: 37.5146,
    longitude: 127.0596,
    budget_level: 'medium',
    description: '고급 디저트 카페',
  },
  {
    id: '43',
    name: 'Noodle Tree',
    nameKo: '국수나무',
    category: 'Korean',
    address: '서울특별시 여러 지역',
    latitude: 37.5295,
    longitude: 127.0241,
    budget_level: 'low',
    description: '한국식 국수 체인점',
  },
  {
    id: '44',
    name: 'Coreanos Kitchen',
    nameKo: '코레아노스키친',
    category: 'Korean Fusion',
    address: '서울특별시 용산구 이태원',
    latitude: 37.5355,
    longitude: 126.9938,
    budget_level: 'medium',
    description: '한국식 타코 전문점',
  },
  {
    id: '45',
    name: 'Loco Quan',
    nameKo: '로꼬꽌',
    category: 'Vietnamese',
    address: '서울특별시 용산구 이태원',
    latitude: 37.5351,
    longitude: 126.9944,
    budget_level: 'low',
    description: '베트남 쌀국수와 반미 전문점',
  },
];

export function filterPlacesByCategory(
  places: Place[],
  category: string | null
): Place[] {
  if (!category) return places;
  return places.filter((p) => p.category === category);
}

export function filterPlacesByBudget(
  places: Place[],
  budget: 'low' | 'medium' | 'high' | null
): Place[] {
  if (!budget) return places;
  return places.filter((p) => p.budget_level === budget);
}

export function filterPlacesByDistance(
  places: Place[],
  userLocation: Coordinates,
  maxDistanceKm: number
): Place[] {
  return places.filter((place) => {
    const distance = calculateDistance(userLocation, {
      latitude: place.latitude,
      longitude: place.longitude,
    });
    return distance <= maxDistanceKm;
  });
}

export function searchPlaces(places: Place[], query: string): Place[] {
  if (!query || query.trim().length === 0) return places;
  const lowerQuery = query.toLowerCase();
  return places.filter(
    (p) =>
      p.name.toLowerCase().includes(lowerQuery) ||
      p.nameKo.includes(query) ||
      p.category.toLowerCase().includes(lowerQuery)
  );
}

export function getAllCategories(): string[] {
  const categories = new Set(MOCK_PLACES.map((p) => p.category));
  return Array.from(categories).sort();
}

const CATEGORY_TRANSLATIONS: Record<string, string> = {
  'Korean BBQ': '한식 바비큐',
  'Korean Traditional': '전통 한식',
  'Korean Fine Dining': '한식 파인다이닝',
  'Korean Temple Food': '사찰 음식',
  'Korean Fusion': '한식 퓨전',
  'Korean Street Food': '한식 길거리 음식',
  Korean: '한식',
  Japanese: '일식',
  Seafood: '해산물',
  Cafe: '카페',
  Dessert: '디저트',
  Italian: '이탈리아 음식',
  'Mexican Fusion': '멕시칸 퓨전',
  Thai: '태국 음식',
  Vietnamese: '베트남 음식',
  French: '프렌치',
};

const BUDGET_TRANSLATIONS: Record<'low' | 'medium' | 'high', string> = {
  low: '저렴',
  medium: '중간',
  high: '고급',
};

export function translateCategory(category: string): string {
  return CATEGORY_TRANSLATIONS[category] ?? category;
}

export function translateBudget(budget: 'low' | 'medium' | 'high'): string {
  return BUDGET_TRANSLATIONS[budget] ?? budget;
}
